# Generated by Django 2.0.5 on 2018-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requirement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpnoncash',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
