# Generated by Django 2.0.5 on 2018-07-13 00:15

from django.db import migrations, models
import service_requirement.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncashrequirement',
            name='week_day',
            field=models.CharField(choices=[(service_requirement.models.WeekDay('Saturday'), 'Saturday'), (service_requirement.models.WeekDay('Sunday'), 'Sunday'), (service_requirement.models.WeekDay('Monday'), 'Monday'), (service_requirement.models.WeekDay('Tuesday'), 'Tuesday'), (service_requirement.models.WeekDay('Wednesday'), 'Wednesday'), (service_requirement.models.WeekDay('Thursday'), 'Thursday'), (service_requirement.models.WeekDay('Friday'), 'Friday')], max_length=17),
        ),
    ]
