# Generated by Django 2.0.5 on 2018-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requirement', '0002_auto_20180526_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrequirement',
            name='donated_fund',
            field=models.IntegerField(default=0),
        ),
    ]
