# Generated by Django 2.0.5 on 2018-05-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_requirement', '0003_auto_20180526_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrequirement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_requirements', to='service_member.Institute'),
        ),
    ]
