# Generated by Django 2.0.5 on 2018-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requirement', '0005_auto_20180526_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='beginning_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='ending_time',
            field=models.TimeField(),
        ),
    ]
