# Generated by Django 2.0.5 on 2018-05-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_member', '0003_auto_20180526_0156'),
        ('service_requirement', '0006_auto_20180526_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncashrequirement',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_cash_requirements', to='service_member.Skill'),
        ),
    ]
