# Generated by Django 2.0.5 on 2018-07-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requirement', '0007_noncashrequirement_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashrequirement',
            name='title',
            field=models.CharField(default='بی\u200cعنوان', max_length=30),
        ),
        migrations.AddField(
            model_name='noncashrequirement',
            name='title',
            field=models.CharField(default='بی\u200cعنوان', max_length=30),
        ),
    ]
