# Generated by Django 2.0.5 on 2018-05-24 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefactor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institute',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute', to=settings.AUTH_USER_MODEL),
        ),
    ]
