# Generated by Django 2.0.5 on 2018-05-25 21:26

from django.db import migrations, models
import django.db.models.deletion
import service_member.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_member', '0002_auto_20180525_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_status', models.CharField(choices=[(service_member.models.ActivationStatus('Rejected'), 'Rejected'), (service_member.models.ActivationStatus('Pending'), 'Pending'), (service_member.models.ActivationStatus('Active'), 'Active')], max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='benefactor',
            name='skill',
        ),
        migrations.AddField(
            model_name='hasskill',
            name='benefactor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='service_member.Benefactor'),
        ),
        migrations.AddField(
            model_name='hasskill',
            name='skill_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='benefactors', to='service_member.Skill'),
        ),
    ]
