# Generated by Django 2.0.5 on 2018-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_member', '0003_auto_20180526_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
