# Generated by Django 2.0.5 on 2018-06-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_member', '0006_auto_20180611_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='image/default-img.png', upload_to='image/'),
        ),
    ]
