# Generated by Django 2.0.5 on 2018-06-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_member', '0007_auto_20180611_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefactor',
            old_name='max_chunk_in_week',
            new_name='max_chunk_in_month',
        ),
    ]
